import { db } from "../server/db";
import { skills } from "../shared/schema";

const sampleSkills = [
  {
    slug: "desktop-control",
    name: "Desktop Control",
    description: "Advanced desktop automation with mouse, keyboard, and screen control",
    longDescription: "The most advanced desktop automation skill for OpenClaw. Provides pixel-perfect mouse control, lightning-fast keyboard input, screen capture, window management, and clipboard operations.",
    authorUsername: "matagul",
    version: "1.0.0",
    category: "automation",
    stars: 0,
    downloads: 22,
    currentUsers: 10,
    allTimeUsers: 0,
    securityScore: 85,
    auditStatus: "verified",
    isVerified: true,
    isFeatured: true,
    features: [
      "Absolute positioning - Move to exact coordinates",
      "Relative movement - Move from current position",
      "Smooth movement - Natural, human-like mouse paths",
      "Click types - Left, right, middle, double, triple clicks",
      "Drag & drop - Drag from point A to point B",
      "Scroll - Vertical and horizontal scrolling",
      "Position tracking - Get current mouse coordinates",
    ],
    tags: ["automation", "desktop", "mouse", "keyboard", "screen"],
  },
  {
    slug: "web-scraper",
    name: "Web Scraper",
    description: "Intelligent web scraping with anti-detection and rate limiting",
    longDescription: "A sophisticated web scraping skill that handles dynamic content, respects robots.txt, and includes built-in rate limiting to avoid detection.",
    authorUsername: "scraperdev",
    version: "2.1.0",
    category: "data",
    stars: 45,
    downloads: 1250,
    currentUsers: 89,
    allTimeUsers: 450,
    securityScore: 78,
    auditStatus: "audited",
    isVerified: true,
    isFeatured: true,
    features: [
      "Dynamic content extraction with JavaScript rendering",
      "Automatic retry with exponential backoff",
      "Proxy rotation support",
      "robots.txt compliance",
      "Structured data output (JSON, CSV)",
    ],
    tags: ["scraping", "web", "data", "automation"],
  },
  {
    slug: "file-organizer",
    name: "File Organizer",
    description: "Automatically organize files by type, date, or custom rules",
    longDescription: "An intelligent file organization skill that watches directories and automatically moves, renames, or categorizes files based on configurable rules.",
    authorUsername: "filemaster",
    version: "1.5.2",
    category: "utility",
    stars: 23,
    downloads: 890,
    currentUsers: 45,
    allTimeUsers: 200,
    securityScore: 92,
    auditStatus: "verified",
    isVerified: true,
    isFeatured: false,
    features: [
      "Watch directories for new files",
      "Organize by file type, date, or size",
      "Custom rule engine with regex support",
      "Duplicate detection and handling",
      "Undo/rollback capability",
    ],
    tags: ["files", "organization", "utility", "automation"],
  },
  {
    slug: "api-connector",
    name: "API Connector",
    description: "Universal REST API client with OAuth and rate limiting",
    longDescription: "Connect to any REST API with built-in authentication handling, rate limiting, and response caching. Supports OAuth 1.0, 2.0, API keys, and custom auth schemes.",
    authorUsername: "apidev",
    version: "3.0.1",
    category: "integration",
    stars: 67,
    downloads: 2340,
    currentUsers: 156,
    allTimeUsers: 890,
    securityScore: 88,
    auditStatus: "verified",
    isVerified: true,
    isFeatured: true,
    features: [
      "OAuth 1.0 and 2.0 support",
      "API key authentication",
      "Automatic rate limiting",
      "Response caching",
      "Retry with backoff",
      "Request/response logging",
    ],
    tags: ["api", "rest", "oauth", "integration"],
  },
  {
    slug: "text-analyzer",
    name: "Text Analyzer",
    description: "NLP-powered text analysis with sentiment and entity extraction",
    longDescription: "Analyze text using state-of-the-art NLP models. Extract entities, determine sentiment, classify topics, and summarize content.",
    authorUsername: "nlpmaster",
    version: "1.2.0",
    category: "ai",
    stars: 34,
    downloads: 678,
    currentUsers: 34,
    allTimeUsers: 150,
    securityScore: 75,
    auditStatus: "audited",
    isVerified: false,
    isFeatured: false,
    features: [
      "Sentiment analysis",
      "Named entity recognition",
      "Topic classification",
      "Text summarization",
      "Language detection",
    ],
    tags: ["nlp", "ai", "text", "analysis", "sentiment"],
  },
  {
    slug: "email-handler",
    name: "Email Handler",
    description: "Send, receive, and process emails with template support",
    longDescription: "A comprehensive email handling skill that supports SMTP, IMAP, and popular email APIs. Includes template rendering and attachment handling.",
    authorUsername: "maildev",
    version: "2.0.0",
    category: "communication",
    stars: 19,
    downloads: 456,
    currentUsers: 23,
    allTimeUsers: 120,
    securityScore: 82,
    auditStatus: "verified",
    isVerified: true,
    isFeatured: false,
    features: [
      "SMTP and IMAP support",
      "Gmail and Outlook API integration",
      "HTML and plain text templates",
      "Attachment handling",
      "Email parsing and filtering",
    ],
    tags: ["email", "smtp", "imap", "communication"],
  },
  {
    slug: "database-manager",
    name: "Database Manager",
    description: "Universal database operations for SQL and NoSQL databases",
    longDescription: "Connect to and manage multiple database types including PostgreSQL, MySQL, MongoDB, and Redis. Execute queries, manage schemas, and perform backups.",
    authorUsername: "dbadmin",
    version: "1.8.0",
    category: "data",
    stars: 52,
    downloads: 1890,
    currentUsers: 78,
    allTimeUsers: 340,
    securityScore: 90,
    auditStatus: "verified",
    isVerified: true,
    isFeatured: true,
    features: [
      "PostgreSQL, MySQL, SQLite support",
      "MongoDB and Redis support",
      "Query builder interface",
      "Schema migrations",
      "Automated backups",
    ],
    tags: ["database", "sql", "nosql", "postgres", "mongodb"],
  },
  {
    slug: "image-processor",
    name: "Image Processor",
    description: "Advanced image manipulation and optimization",
    longDescription: "Process, transform, and optimize images with support for all major formats. Includes resizing, cropping, filters, and format conversion.",
    authorUsername: "imgpro",
    version: "2.3.0",
    category: "media",
    stars: 28,
    downloads: 934,
    currentUsers: 41,
    allTimeUsers: 180,
    securityScore: 71,
    auditStatus: "audited",
    isVerified: false,
    isFeatured: false,
    features: [
      "Resize and crop",
      "Format conversion",
      "Image filters and effects",
      "Metadata extraction",
      "Batch processing",
    ],
    tags: ["image", "media", "processing", "optimization"],
  },
];

async function seed() {
  console.log("Seeding skills...");
  
  for (const skill of sampleSkills) {
    try {
      await db.insert(skills).values(skill).onConflictDoNothing();
      console.log(`  ✓ ${skill.name}`);
    } catch (error) {
      console.error(`  ✗ ${skill.name}:`, error);
    }
  }
  
  console.log("Done!");
  process.exit(0);
}

seed();
